version: "3.3"
services:

    grobid:
      image: "lfoppiano/grobid:0.7.2"
      #image: "grobid/grobid:0.7.2" # uncomment for biggest grobid server

    bibheliotech:
        image: bibheliotech
        build:
            context: .
            args:
                - USER_UID
                - USER_GID
        command: gunicorn --bind 0.0.0.0:5000 bht_web:app
        expose:
            - 5000
        volumes:
            #- .:/home/bibheliotech/BibHelioTech # uncomment for code linking
            - ./DATA:/home/bibheliotech/BibHelioTech/DATA
        depends_on: ['grobid', 'redis']

    nginx:
      image: nginx
      volumes:
        - ./web_nginx.docker.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      depends_on:
        - bibheliotech

    worker:
      image: bibheliotech
      command: python manage.py run_worker
      volumes:
        - ./DATA:/home/bibheliotech/BibHelioTech/DATA
#      volumes:
#        - .:/usr/src/app
#      environment:
#        - APP_SETTINGS=project.server.config.DevelopmentConfig
      depends_on:
        - redis

    redis:
      image: redis:6.2-alpine


