version: "3.3"
services:

    bibheliotech:
        image: bibheliotech
        build:
            context: .
            args:
                - USER_UID
                - USER_GID
        command: gunicorn --bind 0.0.0.0:5000 bht_web:app
        expose:
            - 5000
        volumes:
            #- .:/home/bibheliotech/BibHelioTech # uncomment for code linking
            - ./DATA:/home/bibheliotech/BibHelioTech/DATA
        depends_on:
          grobid:
            condition: service_healthy
          redis:
            condition: service_started

    grobid:
      build:
        context: .
        dockerfile: Dockerfile.grobid
      healthcheck:
        test: ["CMD-SHELL", "curl --fail http://localhost:8070/api/isalive || exit 1"]
        interval: 30s
        timeout: 3s
        retries: 30

    worker:
      image: bibheliotech
      command: python manage.py run_worker
      volumes:
        - ./DATA:/home/bibheliotech/BibHelioTech/DATA
      depends_on:
        - bibheliotech

    nginx:
      image: nginx
      volumes:
        - ./web_nginx.docker.conf:/etc/nginx/conf.d/default.conf
      ports:
        - 80:80
      depends_on:
        - bibheliotech

    redis:
      image: redis:6.2-alpine
#      healthcheck:
#        test: ["CMD", "redis-cli", "ping"]
#        interval: 1s
#        timeout: 3s
#        retries: 30


