version: "3.3"
services:

    bibheliotech:
        image: bibheliotech
        build:
            context: .
            args:
                - USER_UID=1000
                - USER_GID=1000
        command: gunicorn --bind 0.0.0.0:5000 bht_web:app
        ports:
          - "5000:5000"
        expose:
            - 5000
        volumes:
            - bht_data:/home/bibheliotech/BibHelioTech/DATA:rw
        depends_on:
          grobid:
            condition: service_healthy
          redis:
            condition: service_started

    grobid:
      build:
        context: .
        dockerfile: Dockerfile.grobid

    worker:
      image: bibheliotech
      command: python manage.py run_worker
      volumes:
        - bht_data:/home/bibheliotech/BibHelioTech/DATA:rw
      depends_on:
        - bibheliotech

    nginx:
      image: nginx
      volumes:
        - ./ressources/web_nginx.docker.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "80:80"
      depends_on:
        - bibheliotech

    redis:
      image: redis:6.2-alpine


volumes:
  bht_data: