version: "3.3"
services:
    bibheliotech:
        image: bibheliotech
        build:
            context: .
            args:
                - USER_UID
                - USER_GID
        ports:
            - "8000:5000"
        volumes:
            #- .:/home/bibheliotech/BibHelioTech # uncomment for code linking
            - ./DATA:/home/bibheliotech/BibHelioTech/DATA
    grobid:
      image: "lfoppiano/grobid:0.7.2"
      #image: "grobid/grobid:0.7.2" # uncomment for biggest grobid server
